version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 288761769499.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t to-do-ecr .
      - docker tag to-do-ecr:latest 288761769499.dkr.ecr.ap-south-1.amazonaws.com/to-do-ecr:latest
      - echo Creating imagedefinitions.json...
      - echo '[{"name":"to-do-ecr","imageUri":"288761769499.dkr.ecr.ap-south-1.amazonaws.com/to-do-ecr:latest"}]' > imagedefinitions.json
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 288761769499.dkr.ecr.ap-south-1.amazonaws.com/to-do-ecr:latest
      - echo Docker image pushed to ECR successfully!
      - echo Updating ECS service...
    

artifacts:
  files:
    - imagedefinitions.json
