version: 0.2

phases:
  install_dependencies:
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install
  build:
    commands:
     
      - npm run build
 
     

artifacts:
  files:
    - '**/*'
